### ISSUE TITLE
security exception Permission denial

### ISSUE THREAD

**Issue by Kakhramon** [jrvansuita/PickImage#126]
Permission Denial: starting Intent { act=android.intent.action.PICK typ=image/* pkg=com.android.browser cmp=com.android.browser/com.android.fileexplorer.activity.FileActivity } 
I got this error but permissions granted

**Comment by AdPNugroho** [comment]
same issue, maybe something wrong with android browser 
i told my user to uninstall update in browser app, and it works

case with xiaomi devices

**Comment by ProMode7** [comment]
@Kakhramon @okalman you can check my forked version for this issue fix.

**Comment by bekirdursun** [comment]
Hello @ProMode7 

The version you fixed is **com.github.jrvansuita:PickImage:v2.5** right?

**Comment by ProMode7** [comment]
Hi @bekirdursun yes, but the PR is not yet merged to master.

**Comment by bekirdursun** [comment]
@jrvansuita help us :)

**Comment by ProMode7** [comment]
He's inactive from quite some time i guess. If you're stuck and its urgent, you can download/checkout my forked version and add it as a module in your project.

**Comment by GuilhE** [comment]
I've the same problem, but not with Gallery, with Camera instead. On Pixel 3A running Android 11 and API 30 nothing happens when I click on "Camera" (Gallery works).
On another device, a Xiaomi Mi 10 lite 5G running Android 10, clicking the Camera crashes the app, Gallery works. 🤔 

@ProMode7 your PR also solves this?
