### ISSUE TITLE
Preventing picture taken from camera to be saved in the `PickResult` folder

### ISSUE THREAD

**Issue by SebastienFCT** [jrvansuita/PickImage#16]
When the user takes camera pictures from the APP, the last picture taken will be saved in a library subfolder named `PickResult`.

Is there anyway to prevent the user form seeing this folder while selecting a library picture?

**Comment by jrvansuita** [comment]
Of course, I will implement it. Or even better. If you can, create a pull
request.

**Comment by SebastienFCT** [comment]
Thanks for your quick answer!

I'll work on this on my personal time but you may implement it before me ;)

**Comment by jrvansuita** [comment]
Ok, look for PickSetup.setPrivateContent(true). I don't know if it will work for older android versions. In my mind it won't. O OS needs a public image path to return the image but let's try. The default library behavior is setPrivateContent(false). Can you check it in older versions? Another approach we can follow is deleting the public image after using it. So let me know. I haven't took any decisions around this yet because I always use to check the image when debugging the library.

**Comment by jrvansuita** [comment]
commit: 22357887cd523d955fb6deee0218983913439a41
